// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Header");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "Header"
                }, React.createElement("img", {
                      className: "Header-logo",
                      alt: "hatch-react",
                      src: "/img/react.svg",
                      width: "80"
                    }), React.createElement("h1", {
                      className: "Header-title"
                    }, "hatch-react"), React.createElement("p", {
                      className: "Header-subTitle"
                    }, "A React starter kit"), React.createElement("nav", {
                      className: "Header-navigation"
                    }, React.createElement("a", {
                          className: "Header-navigation-item",
                          href: "/"
                        }, "Counter")));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
